### ISSUE TITLE
Eliminate binary trees

### ISSUE THREAD

**Issue by wokalski** [maartenschumacher/MSGameOfLife#3]
@maartenschumacher  Time Profiler clearly shows that binary trees _are_ the problem in the game. Multiple conversions between trees and arrays are simply slow. I tried to solve this issue but I don't know enough about game logics to do it. Namely [this](https://github.com/maartenschumacher/MSGameOfLife/blob/master/GameOfLife/GridViewController.swift#L72) and [this](https://github.com/maartenschumacher/MSGameOfLife/blob/master/GameOfLife/GridViewController.swift#L73) line were too misterious for me to fix it.

**Comment by maartenschumacher** [comment]
@wczekalski You're right. It was cool to make those functions with the binary tree but this is the wrong use case. Maybe `Set` would be appropriate here, since we want to eliminate duplicates and have `union` and `subtract`. Or do you think `Set` is also gonna be slow?

**Comment by maartenschumacher** [comment]
I will also refactor those lines to make them more readable.

**Comment by wokalski** [comment]
set is the fastest one from collection types.

**Comment by wokalski** [comment]
Cool, looking forward to it.

**Comment by wokalski** [comment]
fixed in #4
